pipeline {
    agent    { label 'master' }
    options  { timestamps() }
    stages {
        stage("JobX") {
            steps {
                build job: 'JobX', wait: false
            }
        }
    }
}
