pipeline {
    agent { label 'master' }
    options { timestamps() }
    stages {
        stage('Create') {
            steps {
                jobDsl scriptText: '''freeStyleJob("Publish HTML") {
                    displayName("Publish HTML to Apache")
                    steps {
                      shell(readFileFromWorkspace('publish.sh'))
                    }
                }'''
            }
        }
        stage('Build') {
            steps {
                build 'Publish HTML'
            }
        }
    }
    post {
        always {
            echo 'Done!'
        }
    }
}
